### ISSUE TITLE
Improve our data feed

### ISSUE THREAD

**Issue by dsummersl** [codefordurham/adopt-a-drain#12]
We're missing a lot of drains...we need to expand the TYPE column to include: COMBO INLET, CURB INLET, DROP INLET, DROPS DIRECTLY INTO..., SLAB INLET (except for headwall, endsection, yellow jacket)...all care of Amber's analysis.

**Comment by dsummersl** [comment]
There looks to be a lot that are not accessible to the public - we may want to figure out a way of excluding these.

combo inlet might have sewer.

**Comment by dtbog** [comment]
https://github.com/codefordurham/adopt-a-drain/pull/43
We now have everything but HEADWALL and END SECTION.

Did you (or Amber?) get a sense for how drains are tagged as private?

**Comment by specious** [comment]
This might be affected by #50.

**Comment by specious** [comment]
I asked Sean McKnight, GIS Analyst at [Durham's Stormwater & GIS Services](http://durhamnc.gov/692/Stormwater-GIS-Services/) (he's helped us majorly with locating and understanding the data originally), for input on our progress.  Sean's response:

> From what I can tell in your post the application is still attempting to talk to our
map service that we host here at the City, but we have been changing things around
here over the past month.  I was worried that things would break eventually because
of our changes which is why I thought the use of the Open Data site was a
better option.
>
> Actually during the time we were making some changes/upgrades I had a talk with
the Open Data folks and had them configure their site so future changes on our
side would not affect what is being served out by the Open Data portal.  This
should make the availability of the data much more stable.
>
> At this point the data is available (as you have discovered) on the Durham Open
Data site (and that was kind of a long process but it is there now).  So I
would suggest that application download the data (I think it does a download)
from there instead of referencing our map services (which may change) directly.
>
> I think the next step would be to implement what you suggested in your
recent comment in the following thread (which is to use the Open Data portal
and the API to download the data):
>
> https://github.com/codefordurham/adopt-a-drain/issues/50
>
> If there is anything else you guys need let me know.
