### ISSUE TITLE
Missing Drains

### ISSUE THREAD

**Issue by mcknightsa** [codefordurham/adopt-a-drain#82]
There seem to be stormwater drains missing from the map in some locations.  I have verified that
there are drains there and I am not sure why they are missing from the Adopt-A-Drain map.

Here is the first location that was brought to my attention:  Monticello Avenue.

Essentially any storm drain on a street owned by the City should be showing up.

**Comment by specious** [comment]
Are they missing in the [latest data](https://opendurham.nc.gov/explore/dataset/stormwater-drains/) on the open data portal?

Discussions #12 and #50 are focused on switching to importing data published through the data portal instead of using a [stale snapshot](https://github.com/codefordurham/adopt-a-drain/blob/9e9e521c750c30e37f52c47d98fac7737f4a66ed/lib/tasks/data.rake#L34) included in this git repository.

**Comment by dsummersl** [comment]
I've updated our sync method `bundle exec rake data:load_drains` so that it will sychronize records, and I've run it against the version that we currently have on heroku.

**Comment by specious** [comment]
Commit 43ec02334b033979188057689b9aacfd82cd4cdb, for reference.
